/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;



import static Modelo.Conexion.GetConexion;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Jamartinez
 */
public class FLogin extends javax.swing.JFrame 
{   /**
     * Creates new form InicioSesion
     */
    public FLogin()
    { 
        initComponents();  
    }

    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlBack = new javax.swing.JPanel();
        LblSign = new javax.swing.JLabel();
        SI_JLB_2 = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        SI_JLB_1 = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        TxtContrasena = new javax.swing.JPasswordField();
        BtnSignOut = new javax.swing.JButton();
        PnlVertical = new java.awt.Panel();
        JPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesion");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("InicioSesion"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        setType(java.awt.Window.Type.POPUP);

        PnlBack.setBackground(new java.awt.Color(255, 255, 255));

        LblSign.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LblSign.setText("Inicio Sesion");

        SI_JLB_2.setText("Contraseña");

        SI_JLB_1.setText("Usuario");

        BtnLogin.setText("Iniciar Sesion");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        BtnSignOut.setBackground(new java.awt.Color(0, 153, 255));
        BtnSignOut.setText("X");
        BtnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignOutActionPerformed(evt);
            }
        });

        PnlVertical.setBackground(new java.awt.Color(0, 153, 255));

        JPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N

        javax.swing.GroupLayout PnlVerticalLayout = new javax.swing.GroupLayout(PnlVertical);
        PnlVertical.setLayout(PnlVerticalLayout);
        PnlVerticalLayout.setHorizontalGroup(
            PnlVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlVerticalLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(JPic)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        PnlVerticalLayout.setVerticalGroup(
            PnlVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlVerticalLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(JPic, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPic.getAccessibleContext().setAccessibleName("LblPic");

        javax.swing.GroupLayout PnlBackLayout = new javax.swing.GroupLayout(PnlBack);
        PnlBack.setLayout(PnlBackLayout);
        PnlBackLayout.setHorizontalGroup(
            PnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlBackLayout.createSequentialGroup()
                .addComponent(PnlVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(PnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSignOut, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlBackLayout.createSequentialGroup()
                        .addGroup(PnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(TxtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SI_JLB_2)
                            .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SI_JLB_1)
                            .addComponent(LblSign)
                            .addComponent(BtnLogin))
                        .addGap(58, 58, 58))))
        );
        PnlBackLayout.setVerticalGroup(
            PnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlVertical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PnlBackLayout.createSequentialGroup()
                .addComponent(BtnSignOut)
                .addGap(52, 52, 52)
                .addComponent(LblSign)
                .addGap(19, 19, 19)
                .addComponent(SI_JLB_1)
                .addGap(2, 2, 2)
                .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SI_JLB_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnLogin)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        LblSign.getAccessibleContext().setAccessibleName("LblSign");
        BtnSignOut.getAccessibleContext().setAccessibleName("CerrarSesion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(470, 348));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed

        if(validar_ingreso()==1)
        {
            this.dispose();
            FMenu formformulario1 = new FMenu();
            formformulario1.setVisible(true);
        }
        else
        {

            JOptionPane.showMessageDialog(null, "Acceso denegado:\n"
                + "Por favor ingrese un usuario y/o contraseña correctos", "Acceso denegado",
                JOptionPane.ERROR_MESSAGE);

        };
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void BtnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignOutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSignOutActionPerformed
    public int validar_ingreso()
   {
        String usuario = TxtUsuario.getText();
        String clave = String.valueOf(TxtContrasena.getPassword());

        int resultado = 0;

        String Cadena = "select Usuario, Contrasena from InicioSesion where Usuario = '"+usuario+"' and Contrasena = '"+clave+"'";
        Connection conect = GetConexion();
        try 
        {          
            Statement st = conect.createStatement();
            ResultSet rs = st.executeQuery(Cadena);
            if(rs.next())
            {

            resultado = 1;

            }
        }
        catch (SQLException ex) 
        {
            
          JOptionPane.showMessageDialog(null, ex, "Error de conexión", JOptionPane.ERROR_MESSAGE);

        }
        finally
        {
        try 
        {

            conect.close();

        } 
        catch (SQLException ex) 
        {

            JOptionPane.showMessageDialog(null, ex, "Error de desconexión", JOptionPane.ERROR_MESSAGE);
        }
        
        }
      return resultado;
  }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnLogin;
    public javax.swing.JButton BtnSignOut;
    private javax.swing.JLabel JPic;
    private javax.swing.JLabel LblSign;
    private javax.swing.JPanel PnlBack;
    private java.awt.Panel PnlVertical;
    private javax.swing.JLabel SI_JLB_1;
    private javax.swing.JLabel SI_JLB_2;
    public javax.swing.JPasswordField TxtContrasena;
    public javax.swing.JTextField TxtUsuario;
    // End of variables declaration//GEN-END:variables
}
